name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Install Nix
      uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Build with Nix flake
      run: nix build

    - name: Test build artifact
      run: |
        ls -la result/bin/
        ./result/bin/mychannel --help || echo "Binary created successfully"

    - name: Build with CMake (dev environment)
      run: nix develop -c sh -c "cmake -B build -S . && cmake --build build"

    - name: Test dev build
      run: nix develop -c ./build/mychannel --help || echo "Dev build completed successfully"
